---

# This file is the place for cross-role defaults for all products, and
# common parameters from the infrastructure-deployment phase of the
# build (e.g. CloudFormation). Variables defined here will override
# those defined in `<role>/defaults/main.yml`, although defaults
# should usually be defined there too. For variable precedence
# information see:
#
#    https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html


#
# Vars from environment
#
alb_access_logs_prefix: "{{ lookup('env', 'ALB_ACCESS_LOGS_PREFIX') }}"
aws_region: "{{ lookup('env', 'AWS_REGION') }}"
s3_bucket: "{{ lookup('env', 'S3_BUCKET') }}"
efs_path: "{{ lookup('env', 'EFS_PATH') }}"
proxy_name: "{{ lookup('env', 'PROXY_NAME') }}"
vpc_cidr: "{{ lookup('env', 'VPC_CIDR') }}"

#
# Vars from environment with defaults
#
efs_mountpoint: "{{ lookup('env', 'EFS_MOUNTPOINT') | default('/goaccess_data', true) }}"
goaccess_parse_alb_logs_cron_minutes: "{{ lookup('env', 'GOACCESS_PARSE_ALB_LOGS_CRON_MINUTES') | default('0,30', true) }}"
nginx_allowed_cidr: "{{ lookup('env', 'NGINX_ALLOWED_CIDR') | default('128.117.0.0/16', true) }}"

#
# Derived globals
# 
goaccess_db_root: "{{ efs_mountpoint }}/goaccess_db"
goaccess_last_key_file: "{{ efs_mountpoint }}/last_key"
web_root: "{{ efs_mountpoint }}/www"

#
# Unbound
#

# Where unbound forwards DNS requests to for ucar.edu
atl_unbound_ucar_forward: 8.8.8.8

# Where unbound forwards DNS requests to generally
atl_unbound_forward: 10.0.0.2

#
# Checkmk
#
checkmk_server_version: "{{ lookup('env', 'CHECKMK_SERVER_VERSION') }}"
checkmk_server_edition: cre
checkmk_server_no_log: false
checkmk_server_configure_firewall: false
checkmk_server_cleanup: true
# Site name must be <= 16 chars
checkmk_server_sites:
  - name: checkmk
    version: "{{ checkmk_server_version }}"
    edition: "{{ checkmk_server_edition }}"
    state: 'started'
    update_conflict_resolution: 'abort'
    admin_pw: "{{ lookup('env', 'CHECKMK_ADMIN_PW') }}"
    omd_auto_restart: true
    omd_config:
      - var: AUTOSTART
        value: 'on'

# Create an automation user.
- name: "Create an automation user."
  checkmk.general.user:
    server_url: "http://{{ lookup('amazon.aws.aws_ssm', '/infrastructure/adminserver_private_dns) | from_json }}/"
    site: "checkmk"
    api_user: "registration"
    api_secret: "mysecret"
    name: "registration"
    fullname: "Registration User"
    auth_type: "automation"
    password: "ZGSDHUVDSKJHSDF"
    roles:
      - "registration"
    state: "present"

