---

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: Remove default nginx configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Add nginx configuration
  ansible.builtin.template:  
    src: static-site-config.j2
    dest: /etc/nginx/sites-available/static-site-config
    owner: www-data
    group: www-data
    mode: '0644'

- name: Enable website configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/static-site-config
    dest: /etc/nginx/sites-enabled/static-site-config
    state: link

- name: Ensure nginx is running
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
    


