---

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: Nginx configuration
  ansible.builtin.template:  
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: www-data
    group: www-data
    mode: '0644'

- name: Ensure nginx is running
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
    


