---

- name: Enable apache header module
  ansible.builtin.file:
    src: /etc/apache2/mods-available/headers.load
    dest: /etc/apache2/mods-enabled/headers.load
    state: link
  notify:
    - Restart apache


- name: Install config to restrict apache to ucar and VPC internal networks
  ansible.builtin.copy:
    src: aaa_restrict_access.conf
    dest: /etc/apache2/conf-available/aaa_restrict_access.conf
  notify:
    - Restart apache
 
- name: Enable config to restrict apache
  ansible.builtin.file:
    src: /etc/apache2/conf-available/aaa_restrict_access.conf
    dest: /etc/apache2/conf-enabled/aaa_restrict_access.conf
    state: link
  notify:
    - Restart apache
    
- name: Install apache adminserver site conf file
  ansible.builtin.template:  
    src: adminserver.conf.j2
    dest: /etc/apache2/sites-available/adminserver.conf
    owner: "root"
    group: "root"
    mode: '0644'
  notify:
    - Restart apache

- name: Enable apache adminserver site
  ansible.builtin.file:
    src: /etc/apache2/sites-available/adminserver.conf
    dest: /etc/apache2/sites-enabled/adminserver.conf
    state: link
  notify:
    - Restart apache
    
- name: Add alias for goaccess
  ansible.builtin.blockinfile:
    path: /etc/apache2/mods-enabled/alias.conf
    append_newline: true
    prepend_newline: true
    block: |
      # goaccess
      Alias "/goaccess" "/goaccess_data/www"
      <Directory "/goaccess_data/www">
          Options Indexes FollowSymLinks
          Require all granted
      </Directory>
  notify:
    - Restart apache
      
    

  
