---
collections:
  - name: amazon.aws
    version: "10.1.2"
  - name: ansible.posix
    version: "1.5.4"
  # - name: community.docker
  #   version: "3.9.0"
  # - name: community.general
  #   version: "8.6.0"
  # - name: community.postgresql
  #   version: "3.4.0"
