
# If we don't have X-Forwarded-For, then this is an internal request;
# i.e. from a checkmk client
<If "-z %{HTTP:X-Forwarded-For}">
    Header set AllowAccess 1
</If>

# If we have X-Forwarded-For it must be from the UCAR net
<If "%{HTTP:X-Forwarded-For} =~ /^128\.117\./">
    Header set AllowAccess 1
</If>    

<LocationMatch ".*">
    Require env AllowAccess
</LocationMatch>
