
# If we don't have X-Forwarded-For, then this is an internal request;
# e.g. from a checkmk client
<If "-z %{HTTP:X-Forwarded-For}">
    Require all granted
</If>

# If we have X-Forwarded-For it must be from the UCAR net
<ElseIf "%{HTTP:X-Forwarded-For} =~ /^128\.117\./">
    Require all granted
</ElseIf>    

# Deny
<Else>
    Require all denied
</Else>




