---

# # Create an automation user.
# - name: "Create an automation user."
#   checkmk.general.user:
#     server_url: "http://{{ lookup('amazon.aws.aws_ssm', '/infrastructure/adminserver_private_dns) | from_json }}/"
#     site: "checkmk"
#     api_user: "registration"
#     api_secret: 'qUXf];Di-^{1DvLY}t31RfKkwA%qO4'
#     name: "registration"
#     fullname: "Registration User"
#     auth_type: "automation"
#     password: 'qUXf];Di-^{1DvLY}t31RfKkwA%qO4'
#     roles:
#       - "registration"
#     state: "present"

# # FIXME need to update ~checkmk/etc/htpasswd also; need to specify algo? Failed via cli, worked via web gui
# - name: "Set password for checkmk built-in agent_registration user"
#   ansible.builtin.copy:
#     content: "{{ checkmk_registration_user_secret }}"
#     dest: /omd/sites/checkmk/var/check_mk/web/agent_registration/automation.secret
#     owner: checkmk
#     group: checkmk
#     mode: '0600'
#   notify: Restart checkmk

# Periods are not allowed in folder names
- name: "Create folders per ALB host"
  checkmk.general.folder:
    server_url: "http://{{ ansible_facts['fqdn'] }}/"
    site: checkmk
    api_user: agent_registration
    api_secret: "{{ checkmk_registration_user_secret }}"
    path: "/{{ item | split('.') | first }}"
    name: "{{ item | split('.') | first }}"
    state: present
  loop: "{{ alb_hosts }}"


# FIXME should this be a handler?
- name: "Start activation including foreign changes."
  checkmk.general.activation:
    server_url: "http://{{ ansible_facts['fqdn'] }}/"
    site: checkmk
    api_user: agent_registration
    api_secret: "{{ checkmk_registration_user_secret }}"
    force_foreign_changes: true


- name: Create checkmk registration user
  checkmk.general.user:
    server_url: "http://localhost/"
    site: checkmk
    api_user: "{{ checkmk_registration_user }}"
    api_secret: "{{ checkmk_registration_password }}"
    name: "{{ checkmk_registration_user }}"
    fullname: "{{ checkmk_registration_user }}"
    auth_type: "automation"
    password: "{{ checkmk_registration_password }}"
    roles:
      - "admin"
#      - "agent_registration"
    state: "present"
#    notify: Restart checkmk    
